### ISSUE TITLE
graphsage报错

### ISSUE THREAD

**Issue by yy29260000** [shenweichen/GraphNeuralNetwork#9]
2020-02-04 16:35:37.621143: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "E:\Users\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "E:\Users\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "E:\Users\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Unsupported feed type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Users\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "E:\Users\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\Users\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "E:\Users\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unsupported feed type

（tensorflow==1.4.0）

**Comment by Jone-zc** [comment]
请问解决了吗，我也遇到了这个问题

**Comment by TrWestdoor** [comment]
同样的问题。。。

**Comment by TrWestdoor** [comment]
排查了一下，在 run_graphsage_cora.py 中的 32 行插入：
sample_neigh = np.asarray(sample_neigh, dtype=np.float32)
即可，这里 sample_neigh 的类型有一些错误，调整为 float32 后就可以顺利执行了。但是我测试的结果不是很好，大概 0.45 左右的 accuracy。

**Comment by RongfanLi98** [comment]
> 排查了一下，在 run_graphsage_cora.py 中的 32 行插入：
> sample_neigh = np.asarray(sample_neigh, dtype=np.float32)
> 即可，这里 sample_neigh 的类型有一些错误，调整为 float32 后就可以顺利执行了。但是我测试的结果不是很好，大概 0.45 左右的 accuracy。

@shenweichen please fix this bug like his solution. thx
